- docs/source/boot.rst
- rxos/initramfs/init.in.sh
When kernel boots it will not automatically mount devtmpfs if there is an
initramfs. The init script will mount it, but it did not move the mount point
into the target rootfs making some weird noises during boot.
This patch fixes the issue, and also restores the previously unused and broken
`setup_boot` function.
The documentation is also updated to reflect the changes.
Fixes #28
> Move devtmpfs mountpoint to target rootfs

- rxos/rootfs/etc/init.d/rcS
- rxos/rootfs/etc/profile.d/locale.sh
This patch adds a customized rcS script that sources /etc/profile before
running init scripts, thus allowing custom profile.d files to serve as init
configuration.
A profile.d script is added that sets the LANG environment variable.
> Set system-wide environment before init

- docs/source/rootfs_overlays.rst
- rxos/local/ramfsinit/src/init.cpio.in
- rxos/local/ramfsinit/src/init.in.sh
- rxos/scripts/mksdimage.sh
This patch adds the ability to load arbitrary rootfs overlays that contain
extension and overrides for the base rootfs image. The init script has been
modified to mount and add overlays to the final OverlayFS mount. It does this
by discovering the overlay images on the SD card, and ignores the unmountable
ones.
The mksdimage.sh script was modified such that arbitrary files dropped into the
`$BINARIES_DIR/sdcard-extra` can be added to the SD card image. The intention
is to use this for including overlays in the build.
Fixes #45
> Add the ability to use rootfs overlays

- rxos/local/rxos-utils/src/status.sh
> Suppress `ip addr` output in status script

- rxos/local/lighttpd-config/src/lighttpd.conf
The Lighttpd error page prefix is treated as a string, not path, so missing
traling slashes are not handled. This commit adds the trailing slash so the
custom error pages work.
Fixes #59
> Add trailing slash to error page prefix

- rxos/local/ramfsinit/src/init.cpio.in
- rxos/local/ramfsinit/src/init.in.sh
The FAT32 partition on the SD card is almost guaranteed to get corrupted when
power is yanked. This seems to happen regardless of whether there are writes
going to the partition or not. To handle the corruption, this commit adds
`fsck.vfat` to the initramfs image, and modifies the init script so that it
performs fsck on the boot partition, removes any .REC files that are created by
fsck, and remounts the partition read-only.
Fixes #74
> Perform fsck on boot partition in early userspace

- rxos/local/rxos-utils/rxos-utils.mk
- rxos/local/rxos-utils/src/chbootfsmode.sh
Since boot partition is mounted read-only during early userspace init, this
commit adds a utility script that switches the mount between read-only and
read-write to make read-write access to /boot/ directory easier.
> Add utility to swtich boot partition to rw mode

- rxos/local/lighttpd-config/src/lighttpd.conf
The Lighttpd aliases were missing the trailing slash causing 404 errors for
/direct/ URLs. This patch fixes the configuration file template.
> Fix lighttpd multialias configuration

- rxos/local/lighttpd-config/src/lighttpd.conf
- rxos/local/lighttpd-config/src/modules.conf
Modern browsers usually do not try to download files they can render (e.g.,
video, audio, images, text), when pointed to them using a direct URL. To force
browsers to download, Content-Disposition header is needed. This patch changes
the lighty configuration such that the Content-Disposition header is added to
all /direct/ URLs. As a result, the download button in the UI has a more
natural behavior.
> Make /direct/ URL downloadable

- rxos/local/librarian-config/src/librarian.ini
Since Librarian does not support extending component options in the main
config, this patch copies the defaults from the component config file and
prepends to the blacklist specified by rxOS build config.
> Fix lftp blacklists

- rxos/local/storage-hotplug/Config.in
- rxos/local/storage-hotplug/src/hotplug.storage.sh
This patch fixes the hotplug script so that it uses netcat when communicating
with ONDD and FSAL via their sockets.
> Use nc for accessing sockets

- rxos/local/lighttpd-config/src/lighttpd.conf
Because the direct URls are used in iframes, and other places, and not just for
the download link, the Content-Disposition header may interfere with normal
operation. This patch limits the addition of Content-Disposition to only the
/direct/ URLs that have a dl=1 query string. It is expected that the
application will make use of this to specify which links should have a
Content-Disposition header.
> Only add Content-Disposition to real download URLs

- rxos/local/storage-hotplug/Config.in
The storage hotplug requires netcat to communicate with ONDD and FSAL. This
commit removes dependency on the netcat package as busybox should already be
providing netcat.
> Remove netcat dependency from storage hotplug

- rxos/local/ramfsinit/src/dedupe_cpio.py
The dedupe script in the ramfsinit local package used python3 in the shebang,
but it does nothing pythhon3-specific. This patch changes the shebang to use
genric python so it can be used with python2.
> Do not strctly depend on Python 3

- rxos/local/led-control/S99led
- rxos/local/led-control/src/led_ctrl-i2c.sh
- rxos/local/led-control/src/led_ctrl-sysfs.sh
The hotplug script resets the LED to on after it completes. Due to the way i2c
API works, it is not possible to reset it to blinking mode, and therefore, it's
no feasible to use blinking as default LED state. On the other hand, LED starts
in constant-on state on power-on, so we need some form of indication that would
tell us that something changed (e.g., boot completed).
This patch changes the behavior of the S99led init script such that it blinks
the LED for 60 seconds before switching back to solid-on, therefore giving
enough time for the user to notice boot has completed, while maintaining
consistent LED signaling during hotplug events.
> Make LED signaling consistent

- rxos/local/ramfsinit/src/init.nand.in.sh
This is to handle root cert expiry, and to have a relatively sane starting point in the absence of RTC.
> Fix date to Jan 1 2015 during early init

- rxos/Config.in
Include the config file to list librarian-netinterfaces package in the menu.
> Add missing librarian-netinterfaces package back

- rxos/local/librarian-config/src/librarian.ini
The debug flag controls the `filesystem_checks` parameter in Mako,
which causes a `stat` call on each template prior to rendering, to
check if the timestamp on the sources have changed since the last
time they were compiled. In case the timestamps differ the template
is recompiled. For our purposes it can be safely turned off, which
does provide a significant performance boost.
> Turn debug flag off to improve performance

- rxos/local/lighttpd-config/src/lighttpd.conf
- rxos/local/lighttpd-config/src/modules.conf
- rxos/local/rxos-utils/Config.in
- rxos/local/rxos-utils/rxos-utils.mk
- rxos/local/rxos-utils/src/check.sh
- rxos/local/rxos-utils/src/common.sh
- rxos/local/rxos-utils/src/index.sh
- rxos/local/rxos-utils/src/mount.sh
- rxos/local/rxos-utils/src/net.sh
- rxos/local/rxos-utils/src/status.sh
- rxos/local/rxos-utils/src/top.sh
This commit sets up a new path for lighttpd at /qa/, which allows running CGI
scripts in /usr/share/cgi/. The commit also includes an assortment of CGI
scripts including:
- check : run the status command in brief mode
- top : echo complete output of the top command
- mount : echo mount points
- net : echo network information
The status script has been reworked and now features configurable tests (via
Kconfig), verbose and non-verbose (brief) mode, and a switch to enable echoing
of successful tests (by default it only outputs failed checks now).
> Allow probing system status via CGI

- rxos/local/sdr-config/Config.in
- rxos/local/sdr-config/S90sdr
- rxos/local/sdr-config/sdr-config.mk
- rxos/local/sdr-config/src/sdr.sh
This patch changes the sdr init script such that the sdr binary is started in a
screen session rather than directly. This allows the debug curses UI to be
accessible while the demod is running. This also makes the sdr-config local
package to depend on screen.
A utility script, 'sdr', is provided to allow quick access to the debug UI.
> Run demod in screen to allow access to the debug UI

- .gitignore
- docs/source/building_images/rootfs_overlays.rst
- tools/mkoverlaypkg.sh
- tools/overlay-installer.in.sh
This commit adds a utility script, tools/mkoverlaypkg.sh, which creates overlay
update packages from any overlays in the `out/images/overlays` directory. The
documentation on overlays has been updated to inludes not on using this script
and the naming of the generated package files.
See #110
> Add script for creating overlay updates

- rxos/local/persist-conf/src/persist.sh
- rxos/local/ramfsinit/src/init.cpio.in
- rxos/local/ramfsinit/src/init.nand.in.sh
This patch introuces the following changes:
- When safe mode is enabled either through XIO-P0 or kernel command line, the
early init will create an empty file called SAFEMODE in the root of the root
filesystem
- The persist setup hook will detect the presence of SAFEMODE in the root of
the rootfs completely skip persistence in that case exiting with 0 status
With these changes, we are now able to escape from a situation where a
malformed configuration file can cause the system to become unusable (e.g.,
wrong interfaces configuration leading to complete lack of connectivity, or
system becoming unstable due to some combination of hostapd settings).
See #125
> Do not persist in safemode

- rxos/local/librarian-config/src/librarian.ini
The default path is `tmp/firmware`, changing it to `/tmp/firmware`
> Change save path of uploaded firmware package through librarian

- rxos/local/network-config/src/ap.sh
This commit changes the ap script's start/stop functions to return instead of
exist, and thus fixes the restart command, which did not work due to stop
function exiting early.
> AP restart fix

- rxos/patches/chip/README.rst
- rxos/patches/chip/uboot/0001-uboot-axp209-nocurrentlimit.patch
remove VBUS current limits
disable undervoltage protection
> patch uboot: configure VBUS settings in axp209

- rxos/local/remote-support/S11remotesetup
This patch eliminates the need to have a USB stick (and then a USB hub as well) permanently attached to a CHIP in REMOTE mode.
It adds the following:
- REMOTE_DISABLE file stored on usb stick will force removal of REMOTE on /mnt/conf, and prevent REMOTE configuration.
- REMOTE file stored on usb stick will be copied to /mnt/conf at boot
- REMOTE file in /mnt/conf will be used for actual configuration
To enable remote mode, all that is needed is to boot _once_ with the REMOTE file on an attached USB stick. Similarly, to disable remote mode, all that is needed is to boot once with the REMOTE_DISABLE file on an attached USB stick.
The on-board REMOTE file can later be adopted for a UI based config as well.
> enable onboard storage for REMOTE file

- rxos/local/remote-support/S11remotesetup
deleting the REMOTE config would prevent UI from using it.
> don't delete REMOTE config on USB disable, just rename it

- rxos/local/sdr-config/src/sdrargs.py
sdrargs.py had inverted the logic for interpreting the descrambler value
of the presets. the -w parameter for demod actually disables the
descrambler value, and not enables it.
> Fix sdrargs.py option interpretation

- tools/overlay-installer.in.sh
reduce factors by 10 for each level.
right now each level is 1000, so bash overflows, as it seems it uses signed int (makes sense). 
post this fix, each level is a factor of 100, which ought to be enough for anybody - even emacs!
> fix bash overflow due to large factors

- rxos/local/network-config/network-config.mk
- rxos/local/network-config/src/S99netguard
- rxos/local/network-config/src/netrestart.sh
Instead of containing the sequence of commands in the netguard init
script and within librarian-netinterfaces configuration, it will be
stored only in netrestart.sh
> Add separate script that performs the restarting of the network stack

- rxos/Config.in
- rxos/local/opakwatch/Config.in
- rxos/local/opakwatch/opakwatch.mk
- rxos/local/opakwatch/src/S99opakwatch
- rxos/local/opakwatch/src/opakwatch.sh
- rxos/local/storage-hotplug/src/hotplug.storage.sh
- rxos/local/storage-hotplug/src/oncontentchange.sh
- rxos/local/storage-hotplug/storage-hotplug.mk
opakwatch installs a utility script into /usr/bin/opakwatch and an init
script into /etc/init.d/S99opakwatch. When started the script will watch
a specified directory (using inotify) for newly created files and attempt
to extract them with tar to an also specified destination directory.
> Add opakwatch package

- rxos/Config.in
- rxos/configs/busybox.config
- rxos/local/cleanup/Config.in
- rxos/local/cleanup/S90cleanup
- rxos/local/cleanup/cleanup.mk
- rxos/local/cleanup/src/cleanup.sh
This patch adds a new local package called 'cleanup', which installs a 'S90cleanup' service and a cleanup script that is configured to ensure 200 MiB of free space on `/mnt/internal`. Note that this script only cleans up the *internal storage* so as to prevent accidental deletion of user files on external storage. 
The package is currently not buildroot-configurable in terms of operating parameters.
> Autodelete

- rxos/local/storage-hotplug/src/oncontentchange.sh
- rxos/local/storage-hotplug/storage-hotplug.mk
-f only tests for _ordinary_ files, thus the test always fails.
> check for socket using -S test
